version: '3'

x-logging: &logging
  driver: json-file
  options:
    max-size: "20m"
    max-file: "10"

services:
  zipper:
    build: 
      context: .
      args:
        ENV: ${ENV}
    image: zipper
    container_name: datamap_zipper
    restart: always
    logging: *logging
    env_file:
      - ${ENV}.env
    ports: 
      - '9093:9093'
    expose:
      - '9095'
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:9093/api/v1/health-check/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - gatekeeper_gatekeeper-network

networks:
  gatekeeper_gatekeeper-network:
    driver: bridge
    name: gatekeeper_gatekeeper-network
